name: push

on:
  push:
    branches:
      - master

jobs:
  test:
    run-on: ubuntu-latest
    steps:
      - name: Copy repository
        uses: action/checkout@v2

      - name: Run tests
        run: make ci

  build:
    run-on: ubuntu-latest
    needs: test
    steps:
      - name: Copy repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login in docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: Dockerfile.production
          push: true
          tags: chernenkoivan/devops-for-programmers-project-74:latest

